global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "tenantq-app"
    static_configs:
      - targets: ["app:8001"]

  - job_name: "qdrant"
    metrics_path: /metrics
    static_configs:
      - targets: ["qdrant:6333"]
